version: '3.4'

volumes:
  pgdata:

services:
  pacificprint.shop.db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./PacificPrint.Shop.Data/Scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql" 
    ports:
      - 5432:5432
  pacificprint.shop.api:
    image: ${DOCKER_REGISTRY-}pacificprintshopapi
    build:
      context: .
      dockerfile: PacificPrintShop.API/Dockerfile
